<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../QueryShape.SampleApp/QueryShape.SampleApp.csproj" />
    <ProjectReference Include="../../src/QueryShape.Testing/QueryShape.Testing.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>
</Project>
