<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TestFramework>nunit</TestFramework>
    <RootNamespace>QueryShape.Testing.NUnit.Tests</RootNamespace>
    <NoWarn>$(NoWarn);CA1001;CA1515</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/QueryShape.Testing.NUnit/QueryShape.Testing.NUnit.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>
</Project>
