<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/QueryShape.Cli/QueryShape.Cli.csproj" />
    <ProjectReference Include="../QueryShape.Core.Tests/QueryShape.Core.Tests.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>
</Project>
