// Generated by QueryShape. The replay helper must recreate an isolated fixture and return true only for the original failure.
// This test is expected to fail until that failure is fixed.
public sealed class QueryShapeRegression_3edc1623f68946ae9c2125d0376e7671
{
    [global::Xunit.Fact]
    public async global::System.Threading.Tasks.Task Reduced_case_preserves_behavior()
    {
        const string inputJson = "[\n  {\n    \u0022Id\u0022: 7,\n    \u0022HasPhone\u0022: false\n  }\n]";
        if (await global::ContributorTests.StillDropsContributorAsync(inputJson, global::System.Threading.CancellationToken.None))
            throw new global::System.InvalidOperationException("QueryShape reduced failure still reproduces.");
    }
}
