// Generated by QueryShape. The replay helper must recreate an isolated fixture and return true only for the original failure.
// This test is expected to fail until that failure is fixed.
public sealed class QueryShapeRegression_300d75c053c8447db5e6513f58a10a13
{
    [global::Xunit.Fact]
    public async global::System.Threading.Tasks.Task Reduced_case_preserves_behavior()
    {
        const string inputJson = "501";
        if (await global::ScenarioTests.BasketWarningStillReproducesAsync(inputJson, global::System.Threading.CancellationToken.None))
            throw new global::System.InvalidOperationException("QueryShape reduced failure still reproduces.");
    }
}
