<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <IsTestProject>false</IsTestProject>
    <IsSampleApp>true</IsSampleApp>
    <RootNamespace>QueryShape.Benchmarks</RootNamespace>
    <NoWarn>$(NoWarn);CA1822;CA1515;CA2007;CA1001;CA1063;CA1816</NoWarn>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/QueryShape.Core/QueryShape.Core.csproj" />
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <ProjectReference Include="../QueryShape.SampleApp/QueryShape.SampleApp.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>
</Project>
