<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TestFramework>xunit.v3</TestFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>QueryShape.Testing.Xunit.V3.Tests</RootNamespace>
    <NoWarn>$(NoWarn);CA1001;CA1515</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/QueryShape.Testing.Xunit.v3/QueryShape.Testing.Xunit.v3.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" />
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
  </ItemGroup>
</Project>
