using System.Globalization;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace QueryShape.Testing;

/// <summary>A reduction trial. Only a matching failure signature is retained; invalid datasets are skipped.</summary>
public sealed record ReductionTrial(bool Valid, string? Failure)
{
    public static ReductionTrial Pass { get; } = new(true, null);
    public static ReductionTrial Invalid { get; } = new(false, null);
    public static ReductionTrial Fail(string signature)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(signature);
        return new(true, signature);
    }
}

public enum RegressionFramework
{
    Xunit,
    NUnit,
    MSTest,
}

public sealed class ReductionOptions
{
    public int MaxAttempts { get; init; } = 200;
    public int Confirmations { get; init; } = 2;
    /// <summary>Optional artifact directory. Input JSON is written only when explicitly requested here or by the CLI.</summary>
    public string? ArtifactDirectory { get; init; }
    /// <summary>Fully qualified static method accepting (string inputJson, CancellationToken) and returning Task&lt;bool&gt; (true means the original failure persists).</summary>
    public string? ReplayMethod { get; init; }
    public RegressionFramework Framework { get; init; }
}

public sealed record ReductionSummary(string Name, string Failure, long OriginalComplexity, long ReducedComplexity, int Attempts, bool Complete, string? RegressionFile)
{
    public bool Passed => Complete;
    public string ToJson() => JsonSerializer.Serialize(this, new JsonSerializerOptions(JsonSerializerDefaults.Web) { WriteIndented = true });
    public string ToText() => $"QueryShape reduction: {Name}\nFailure: {Failure}\nComplexity: {OriginalComplexity} -> {ReducedComplexity}\nTrials: {Attempts}\n" +
        (Complete ? "No smaller reproducer among the supplied candidates.\n" : "Attempt budget exhausted; this reproducer may shrink further.\n") +
        (RegressionFile is null ? string.Empty : "Regression test: " + RegressionFile + "\n");
}

public sealed record ReductionResult<T>(T Input, ReductionSummary Summary)
{
    /// <summary>Writes a JSON reproducer and compilable test calling the supplied application-specific replay helper. Existing files are never replaced.</summary>
    public async Task<string> WriteRegressionAsync(string directory, string replayMethod, RegressionFramework framework = RegressionFramework.Xunit,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(directory);
        ArgumentException.ThrowIfNullOrWhiteSpace(replayMethod);
        if (!Regex.IsMatch(replayMethod, @"^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)+$", RegexOptions.CultureInvariant))
            throw new ArgumentException("Use a fully qualified static replay method, for example MyTests.Cases.StillFailsAsync.", nameof(replayMethod));
        if (!Enum.IsDefined(framework)) throw new ArgumentOutOfRangeException(nameof(framework));
        var input = JsonSerializer.Serialize(Input, new JsonSerializerOptions { WriteIndented = true });
        var className = "QueryShapeRegression_" + Guid.NewGuid().ToString("N");
        var attribute = framework switch
        {
            RegressionFramework.NUnit => "[global::NUnit.Framework.Test]",
            RegressionFramework.MSTest => "[global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethod]",
            _ => "[global::Xunit.Fact]",
        };
        var classAttribute = framework == RegressionFramework.MSTest ? "[global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClass]\n" : string.Empty;
        var source = $$"""
            // Generated by QueryShape. The replay helper must recreate an isolated fixture and return true only for the original failure.
            // This test is expected to fail until that failure is fixed.
            {{classAttribute}}public sealed class {{className}}
            {
                {{attribute}}
                public async global::System.Threading.Tasks.Task Reduced_case_preserves_behavior()
                {
                    const string inputJson = {{JsonSerializer.Serialize(input)}};
                    if (await global::{{replayMethod}}(inputJson, global::System.Threading.CancellationToken.None))
                        throw new global::System.InvalidOperationException("QueryShape reduced failure still reproduces.");
                }
            }
            """;
        Directory.CreateDirectory(directory);
        var path = Path.Combine(directory, className + ".cs");
        await WriteNewAsync(Path.ChangeExtension(path, ".json"), input + "\n", cancellationToken).ConfigureAwait(false);
        await WriteNewAsync(path, source.Replace("\r\n", "\n", StringComparison.Ordinal) + "\n", cancellationToken).ConfigureAwait(false);
        return path;
    }

    private static async Task WriteNewAsync(string path, string content, CancellationToken ct)
    {
        await using var file = new FileStream(path, FileMode.CreateNew, FileAccess.Write);
        await using var writer = new StreamWriter(file, new System.Text.UTF8Encoding(false));
        await writer.WriteAsync(content.AsMemory(), ct).ConfigureAwait(false);
    }
}

/// <summary>Deterministic reduction over application-provided valid candidates. Exceptions/cancellation are never interpreted as a reproducing failure.</summary>
public static class QueryReduction
{
    public static async Task<ReductionResult<T>> MinimizeAsync<T>(string name, T input, Func<T, IEnumerable<T>> candidates,
        Func<T, long> complexity, Func<T, CancellationToken, Task<ReductionTrial>> evaluateAsync,
        ReductionOptions? options = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);
        ArgumentNullException.ThrowIfNull(candidates);
        ArgumentNullException.ThrowIfNull(complexity);
        ArgumentNullException.ThrowIfNull(evaluateAsync);
        options ??= new ReductionOptions();
        var budget = Environment.GetEnvironmentVariable("QUERYSHAPE_REDUCTION_ATTEMPTS") is { Length: > 0 } limit
            ? int.Parse(limit, CultureInfo.InvariantCulture) : options.MaxAttempts;
        if (options.Confirmations is < 1 or > 20 || budget < options.Confirmations) throw new ArgumentOutOfRangeException(nameof(options));
        var originalSize = complexity(input);
        if (originalSize < 0) throw new ArgumentOutOfRangeException(nameof(input), "Complexity must be nonnegative.");
        var attempts = 0;
        string? failure = null;
        for (var i = 0; i < options.Confirmations; i++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var trial = await evaluateAsync(input, cancellationToken).ConfigureAwait(false);
            attempts++;
            if (!trial.Valid || string.IsNullOrWhiteSpace(trial.Failure) || (failure is not null && failure != trial.Failure))
                throw new InvalidOperationException("The initial input must consistently reproduce one named failure.");
            failure = trial.Failure;
        }

        var current = input;
        var currentSize = originalSize;
        var complete = false;
        while (true)
        {
            var reduced = false;
            var exhausted = false;
            var inspected = 0;
            foreach (var candidate in candidates(current))
            {
                cancellationToken.ThrowIfCancellationRequested();
                // Also bound invalid/non-shrinking candidate enumeration, not just database executions.
                if (++inspected > budget) { exhausted = true; break; }
                var size = complexity(candidate);
                if (size < 0 || size >= currentSize) continue;
                if (attempts + options.Confirmations > budget) { exhausted = true; break; }
                var retainsFailure = true;
                for (var check = 0; check < options.Confirmations; check++)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    var trial = await evaluateAsync(candidate, cancellationToken).ConfigureAwait(false);
                    attempts++;
                    if (!trial.Valid || trial.Failure != failure) { retainsFailure = false; break; }
                }
                if (!retainsFailure) continue;
                current = candidate;
                currentSize = size;
                reduced = true;
                break;
            }
            if (exhausted) break;
            if (!reduced) { complete = true; break; }
        }

        var summary = new ReductionSummary(name, failure!, originalSize, currentSize, attempts, complete, null);
        var result = new ReductionResult<T>(current, summary);
        var directory = Environment.GetEnvironmentVariable("QUERYSHAPE_REDUCTION_DIR") ?? options.ArtifactDirectory;
        if (directory is not null)
        {
            if (options.ReplayMethod is null) throw new InvalidOperationException("Set ReductionOptions.ReplayMethod to generate a regression test.");
            var path = await result.WriteRegressionAsync(directory, options.ReplayMethod, options.Framework, cancellationToken).ConfigureAwait(false);
            result = result with { Summary = summary with { RegressionFile = path } };
        }
        using var scope = QueryShapeScope.Begin(name + "/reduction");
        scope.Annotate("reduction.report", result.Summary.ToJson());
        return result;
    }

    /// <summary>Chunk deletion followed by single-element deletion. For related rows, supply a generator that also preserves foreign keys.</summary>
    public static IEnumerable<IReadOnlyList<T>> RemoveChunks<T>(IReadOnlyList<T> input)
    {
        ArgumentNullException.ThrowIfNull(input);
        if (input.Count == 0) yield break;
        yield return Array.Empty<T>();
        for (var chunk = Math.Max(1, input.Count / 2); ; chunk = Math.Max(1, chunk / 2))
        {
            for (var start = 0; start < input.Count; start += chunk)
                yield return input.Where((_, i) => i < start || i >= start + chunk).ToArray();
            if (chunk == 1) break;
        }
    }
}
